name: Scheduled Vector Store Update

on:
  schedule:
    - cron: '0 1 * * *'  # Runs every day at 1 am UTC
  workflow_dispatch:

jobs:
  scrape_job:
    runs-on: ubuntu-latest  # Use a Linux runner environment

    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a requirements.txt file

      - name: Run scraping script
        run: |
          python backend/scripts/update_vector_store.py
